export const CHANGE_USERNAME = 'login/CHANGE_USERNAME'
export const CHANGE_PASSWORD = 'login/CHANGE_PASSWORD'
export const LOGIN = 'login/LOGIN'
export const CHANGE_LOGIN = 'login/CHANGE_LOGIN'
export const logout = 'login/logout'
